version: '3.8'
services:
  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pass1234
      DB_NAME: contactdb
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: contactdb
    ports:
      - "5433:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
