version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=contactdb
    ports:
      - "5433:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@db:5432/contactdb?sslmode=disable
    depends_on:
      - db
    entrypoint:
      [
        "/app/wait-for.sh",
        "db:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
